### ISSUE TITLE
`cmd/governctl`: Segmentation fault when merging a PR while under review

### ISSUE THREAD

**Issue by razvand** [unikraft/governance#27]
Using `cmd/governctl` to merge a pull request while under review (i.e. one reviewer is still pending with their review) results in segmentation fault.

See below a sample run:

```console
$ governctl pr merge --approve-states "${GOVERN_APPROVE_STATES}" --review-states "${GOVERN_REVIEW_STATES}" --base "staging" --push "unikraft/unikraft/1137"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9c544d]

goroutine 1 [running]:
github.com/unikraft/governance/internal/ghpr.(*PullRequest).SatisfiesMergeRequirements(0xc00013bb00, {0xc8f5b8, 0xc0001cf6b0}, {0xc004d077c0, 0x10, 0xc0001321d0?})
	/__w/governance/governance/internal/ghpr/ghpr_mergable.go:56 +0x46d
github.com/unikraft/governance/cmd/governctl/pr.(*Merge).Run(0xc000144480, {0xc8f5b8, 0xc0001cf6b0}, {0xc00013ba80?, 0x0?, 0x0?})
	/__w/governance/governance/cmd/governctl/pr/merge.go:119 +0x945
kraftkit.sh/cmdfactory.New.func1(0xc0001c3800?, {0xc00013ba80?, 0x0?, 0x0?})
	/go/pkg/mod/kraftkit.sh@v0.7.1/cmdfactory/builder.go:365 +0x43
kraftkit.sh/cmdfactory.AttributeFlags.bind.func3(0x0?, {0xc00013ba80, 0x1, 0x8})
	/go/pkg/mod/kraftkit.sh@v0.7.1/cmdfactory/builder.go:547 +0x1b6
kraftkit.sh/cmdfactory.AttributeFlags.bind.func3(0xc0001d4000?, {0xc00013ba80, 0x1, 0x8})
	/go/pkg/mod/kraftkit.sh@v0.7.1/cmdfactory/builder.go:547 +0x1b6
github.com/spf13/cobra.(*Command).execute(0xc0001c3800, {0xc00013ba00, 0x8, 0x8})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c2000)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).ExecuteC(0x1?)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1012 +0x54a
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
kraftkit.sh/cmdfactory.Main({0xc8f5b8?, 0xc0001cf6b0}, 0xc0001c3800)
	/go/pkg/mod/kraftkit.sh@v0.7.1/cmdfactory/builder.go:183 +0x74
main.main()
	/__w/governance/governance/cmd/governctl/main.go:100 +0x2ef
```

**Comment by craciunoiuc** [comment]
Added a `nil` check for that, should at least to panic anymore, let me know if it happens again
